name: Build and Publish CUDA Wheel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner as env var
        id: lower-owner
        run: echo "REPO_OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check if wheel already exists
        id: check-wheel
        run: |
          mkdir -p wheel
          if compgen -G "wheel/*.whl" > /dev/null; then
            echo "WHEEL_EXISTS=true" >> $GITHUB_ENV
          else
            echo "WHEEL_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image (only if wheel not found)
        if: env.WHEEL_EXISTS == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LC }}/tla-builder:latest
          platforms: linux/amd64
          outputs: type=local,dest=wheel

      - name: Upload wheel to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cuda-wheel-${{ github.sha }}
          name: "CUDA Wheel Build - ${{ github.sha }}"
          files: wheel/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
